### ISSUE TITLE
Where USER_TOKEN

### ISSUE THREAD

**Issue by nonameformr** [axle-h/Axh.Fit.Endomondo#2]
Where get the USER_TOKEN ?

**Comment by Eriboyz** [comment]
For Mozilla Firefox: When you open the endomondo website, press Shift + F9. You will find the line USER_TOKEN below. Double click and copy. Then insert it behind the line `Axh.Fit.Endomondo -gu`. Good luck!

**Comment by axle-h** [comment]
Chrome it's F12 -> Application -> Cookies -> https://www.endomondo.com
https://developers.google.com/web/tools/chrome-devtools/storage/cookies
